# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-27 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181221_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'prov', 'verbose_name_plural': 'prov'},
        ),
        migrations.AlterField(
            model_name='user',
            name='fixtel',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='固定电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='qq'),
        ),
    ]
